clover:
  image: coderfox/clover:latest
  container_name: clover
  privileged: false
  volumes:
  - ./clover.db:/app/clover.db
  - ./config/v2ray_server.json:/app/config/v2ray_server.json
  - /var/run/docker.sock:/var/run/docker.sock:ro
  expose:
  - 3000
v2ray:
  image: v2ray/official
  container_name: v2ray
  privileged: false
  ports:
  - 443
  volumes:
  - ./config/v2ray_server.json:/etc/v2ray/config.json